name: wsf
channels:
  - default
  - anaconda
  - conda-forge
dependencies:
  - python
  - ipython
  - ipykernel
  - jupyter
  - pandas >=1.0
  - plotly
  - dash
  - ffmpeg
  - beautifulsoup4
  - requests
  - lxml
  - flake8
  - black
